//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SortList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disc
    {
        public int Id { get; set; }
        public string discipline { get; set; }
    
        public virtual litr litr { get; set; }
    }
}
